/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "secondary-container": "#ad009b",
        "surface-dim": "#0e0e14",
        "surface-variant": "#25252e",
        "on-tertiary-fixed-variant": "#003b66",
        "primary-container": "#00f1fe",
        "secondary-dim": "#ff59e3",
        "tertiary": "#6fb5ff",
        "on-surface-variant": "#acaab3",
        "on-primary-fixed": "#004145",
        "on-tertiary-container": "#002746",
        "primary-fixed-dim": "#00e2ee",
        "error": "#ff716c",
        "surface-container-lowest": "#000000",
        "on-primary-fixed-variant": "#006065",
        "surface": "#0e0e14",
        "outline-variant": "#48474f",
        "surface-container": "#191921",
        "primary-fixed": "#00f1fe",
        "background": "#0e0e14",
        "on-secondary-fixed": "#640059",
        "secondary-fixed-dim": "#ffa8e7",
        "on-secondary": "#42003a",
        "secondary": "#ff59e3",
        "primary": "#99f7ff",
        "on-secondary-fixed-variant": "#950085",
        "on-secondary-container": "#fff5f8",
        "on-error-container": "#ffa8a3",
        "surface-container-low": "#13131a",
        "tertiary-dim": "#47a2f8",
        "on-tertiary-fixed": "#001930",
        "surface-tint": "#99f7ff",
        "primary-dim": "#00e2ee",
        "surface-container-highest": "#25252e",
        "inverse-surface": "#fcf8ff",
        "on-primary": "#005f64",
        "error-container": "#9f0519",
        "on-surface": "#f6f2fc",
        "inverse-primary": "#006a70",
        "outline": "#76747d",
        "on-tertiary": "#003258",
        "tertiary-container": "#4da8fe",
        "error-dim": "#d7383b",
        "inverse-on-surface": "#55545c",
        "tertiary-fixed": "#6fb5ff",
        "secondary-fixed": "#ffbeeb",
        "on-error": "#490006",
        "tertiary-fixed-dim": "#4da8fe",
        "surface-container-high": "#1f1f27",
        "surface-bright": "#2b2b35",
        "on-primary-container": "#00555a",
        "on-background": "#f6f2fc"
      },
      "fontFamily": {
        "headline": ["Space Grotesk"],
        "body": ["Manrope"],
        "label": ["Space Grotesk"]
      }
    },
  },
  plugins: [],
}
